default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: api_zip_code_development

test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: api_zip_code_test

production:
  <<: *default
  database: api_zip_code_production
  username: api_zip_code
  password: <%= ENV["API_ZIP_CODE_DATABASE_PASSWORD"] %>
